# Generated by Django 4.2.10 on 2024-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='canvas_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='retinaphoto',
            name='image',
            field=models.ImageField(upload_to='retina_images/'),
        ),
    ]
