# Generated by Django 4.2.10 on 2024-03-24 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blindness_detection', '0003_canvasimage_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasimage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canvas_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
