# Generated by Django 4.2.10 on 2024-03-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0005_alter_canvasimage_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradcamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='retina_gradcam_images/')),
            ],
        ),
    ]
