# Generated by Django 4.2.10 on 2024-03-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0006_gradcamimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_label', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1)),
                ('image_name', models.CharField(max_length=255)),
            ],
        ),
    ]
