# Generated by Django 4.2.10 on 2024-03-24 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0007_correctlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctlabel',
            name='image_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_labels', to='blindness_detection.retinaphoto'),
        ),
    ]
