# Generated by Django 4.2.10 on 2024-03-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0008_alter_correctlabel_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctlabel',
            name='image_name',
            field=models.CharField(max_length=255),
        ),
    ]
