# Generated by Django 4.2.10 on 2024-03-30 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blindness_detection', '0009_alter_correctlabel_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='retinaphoto',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correctlabel',
            name='correct_label',
            field=models.CharField(choices=[('No DR', 'No DR'), ('Mild DR', 'Mild DR'), ('Moderate DR', 'Moderate DR'), ('Severe DR', 'Severe DR'), ('Proliferative DR', 'Proliferative DR')], default='No DR', max_length=100),
        ),
    ]
