# Generated by Django 4.2.10 on 2024-03-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0011_alter_canvasimage_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradcamimage',
            name='retina_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gradcam_images', to='blindness_detection.retinaphoto'),
            preserve_default=False,
        ),
    ]
