# Generated by Django 4.2.10 on 2024-03-31 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0013_alter_gradcamimage_retina_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasimage',
            name='retina_photo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_image', to='blindness_detection.retinaphoto'),
            preserve_default=False,
        ),
    ]
