# Generated by Django 4.2.10 on 2024-04-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0018_zipfile2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZipFile2',
            new_name='ZipFile',
        ),
    ]
