# Generated by Django 4.2.10 on 2024-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0020_zipfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipfile',
            name='name',
        ),
        migrations.AddField(
            model_name='zipfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='zip_files/'),
        ),
    ]
