# Generated by Django 4.2.10 on 2024-04-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0021_remove_zipfile_name_zipfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipFile',
        ),
    ]
