# Generated by Django 4.2.10 on 2024-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0022_delete_zipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctlabel',
            name='correct_label',
            field=models.CharField(choices=[('No Diabetic Retinopathy', 'No Diabetic Retinopathy'), ('Mild Diabetic Retinopathy', 'Mild Diabetic Retinopathy'), ('Moderate Diabetic Retinopathy', 'Moderate Diabetic Retinopathy'), ('Severe Diabetic Retinopathy', 'Severe Diabetic Retinopathy'), ('Proliferative Diabetic Retinopathy', 'Proliferative Diabetic Retinopathy')], default='No Diabetic Retinopathy', max_length=100),
        ),
    ]
