# Generated by Django 4.2.10 on 2024-05-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0023_alter_correctlabel_correct_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retina_photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='blindness_detection.retinaphoto')),
            ],
        ),
    ]
