# Generated by Django 4.2.10 on 2024-07-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0025_retinaphoto_dob_retinaphoto_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='retinaphoto',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='retinaphoto',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='retinaphoto',
            name='location',
        ),
        migrations.RemoveField(
            model_name='retinaphoto',
            name='name',
        ),
    ]
