# Generated by Django 4.2.10 on 2024-07-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0028_alter_canvasimage_retina_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='retina_photo',
        ),
    ]
