# Generated by Django 4.2.10 on 2024-07-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0029_remove_report_retina_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasimage',
            name='retina_photo',
        ),
        migrations.RemoveField(
            model_name='correctlabel',
            name='retina_photo',
        ),
        migrations.RemoveField(
            model_name='gradcamimage',
            name='retina_photo',
        ),
    ]
