# Generated by Django 4.2.10 on 2024-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0030_remove_canvasimage_retina_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
