# Generated by Django 4.2.10 on 2024-07-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blindness_detection', '0032_gradcamimage_retina_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasimage',
            name='retina_photo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_image', to='blindness_detection.patient'),
            preserve_default=False,
        ),
    ]
