# Generated by Django 4.2.10 on 2024-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default-profile-picture.png', upload_to='profile_pictures/'),
        ),
    ]
